---
- name: Install MariaDB server packages
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-client
    - MariaDB-server
    - galera

- name: Install MySQL-python
  yum: name=MySQL-python state=present
